name: rpi
version: "1.0.0"
profile: rpi

model-paths: ["models"]
test-paths: ["tests_dbt"]
seed-paths: ["seeds"]

models:
  rpi:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table